// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Timer(Props) {
  var match = React.useReducer((function (state, action) {
          switch (action) {
            case 0 : 
                return /* record */[
                        /* seconds */state[/* seconds */0],
                        /* isTicking */true
                      ];
            case 1 : 
                return /* record */[
                        /* seconds */state[/* seconds */0],
                        /* isTicking */false
                      ];
            case 2 : 
                return /* record */[
                        /* seconds */30,
                        /* isTicking */state[/* isTicking */1]
                      ];
            case 3 : 
                return /* record */[
                        /* seconds */state[/* seconds */0] - 1 | 0,
                        /* isTicking */state[/* isTicking */1]
                      ];
            
          }
        }), /* record */[
        /* seconds */30,
        /* isTicking */false
      ]);
  return React.createElement("div", undefined, "There are" + (String(match[0][/* seconds */0]) + "one the clock"));
}

var make = Timer;

exports.make = make;
/* react Not a pure module */
